FROM       cyberdojo/java-1.8
MAINTAINER Jon Jagger <jon@jaggersoft.com>

# build-essential was built from 13.10 (saucy)
RUN echo "deb http://archive.ubuntu.com/ubuntu saucy main universe" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get upgrade -y

RUN apt-get install -y curl
RUN curl -s get.gvmtool.net | bash
RUN gvm install groovy

# docker build -t  cyberdojo/groovy .
# docker push      cyberdojo/groovy
# docker run -i -t cyberdojo/groovy /bin/bash