FROM       cyberdojofoundation/java-1.8
MAINTAINER Jon Jagger <jon@jaggersoft.com>

COPY cucumber-core-1.1.6.jar /cucumber/
COPY cucumber-html-0.2.3.jar /cucumber/
COPY cucumber-java-1.1.6.jar /cucumber/
COPY cucumber-junit-1.1.6.jar /cucumber/
COPY cucumber-jvm-deps-1.0.3.jar /cucumber/
COPY cucumber-picocontainer-1.1.6.jar /cucumber/
COPY gherkin-2.12.2.jar /cucumber/
COPY hamcrest-core-1.3.jar /cucumber/
COPY junit-4.11.jar /cucumber/
COPY picocontainer-2.14.2.jar /cucumber/

ENV CLASSPATH=/cucumber/
