FROM       cyberdojofoundation/java-1.8
MAINTAINER Jon Jagger <jon@jaggersoft.com>

ADD cucumber-core-1.1.6.jar /cucumber/
ADD cucumber-html-0.2.3.jar /cucumber/
ADD cucumber-java-1.1.6.jar /cucumber/
ADD cucumber-junit-1.1.6.jar /cucumber/
ADD cucumber-jvm-deps-1.0.3.jar /cucumber/
ADD cucumber-picocontainer-1.1.6.jar /cucumber/
ADD gherkin-2.12.2.jar /cucumber/
ADD hamcrest-core-1.3.jar /cucumber/
ADD junit-4.11.jar /cucumber/
ADD picocontainer-2.14.2.jar /cucumber/

ENV CLASSPATH=/cucumber/
