FROM       cyberdojofoundation/java-1.8
MAINTAINER Jon Jagger <jon@jaggersoft.com>

ADD cglib-nodep-2.2.2.jar /powermockito/
ADD javassist-3.18.1-GA.jar /powermockito/
ADD junit-4.11.jar /powermockito/
ADD mockito-all-1.9.5.jar /powermockito/
ADD objenesis-2.1.jar /powermockito/
ADD powermock-mockito-1.5.4-full.jar /powermockito/

ENV CLASSPATH=/powermockito/

