FROM       cyberdojo/build-essential
MAINTAINER Jon Jagger <jon@jaggersoft.com>

# docker build -t  cyberdojo/language_gcc-4.8.1_assert .
# docker push      cyberdojo/language_gcc-4.8.1_assert
# docker run -i -t cyberdojo/language_gcc-4.8.1_assert /bin/bash
