
$HOME_DIR = File.expand_path('..', File.dirname(__FILE__))

$APP_HELPERS_DIR = $HOME_DIR + '/app/helpers'
$APP_LIB_DIR     = $HOME_DIR + '/app/lib'
$APP_MODELS_DIR  = $HOME_DIR + '/app/models'
$LIB_DIR         = $HOME_DIR + '/lib'

require $APP_HELPERS_DIR + '/avatar_image_helper'
require $APP_HELPERS_DIR + '/logo_image_helper'
require $APP_HELPERS_DIR + '/make_time_helper'
require $APP_HELPERS_DIR + '/parity_helper'
require $APP_HELPERS_DIR + '/pie_chart_helper'
require $APP_HELPERS_DIR + '/traffic_light_helper'

require $APP_LIB_DIR + '/Approval'
require $APP_LIB_DIR + '/Choose'
require $APP_LIB_DIR + '/Cleaner'
require $APP_LIB_DIR + '/FileDeltaMaker'
require $APP_LIB_DIR + '/GitDiff'
require $APP_LIB_DIR + '/GitDiffBuilder'
require $APP_LIB_DIR + '/GitDiffParser'
require $APP_LIB_DIR + '/LineSplitter'
require $APP_LIB_DIR + '/MakefileFilter'
require $APP_LIB_DIR + '/OutputParser'
require $APP_LIB_DIR + '/TdGapper'

require $APP_MODELS_DIR + '/Dojo'
require $APP_MODELS_DIR + '/Languages'
require $APP_MODELS_DIR + '/Language'
require $APP_MODELS_DIR + '/Exercises'
require $APP_MODELS_DIR + '/Exercise'
require $APP_MODELS_DIR + '/Katas'
require $APP_MODELS_DIR + '/Kata'
require $APP_MODELS_DIR + '/Id'
require $APP_MODELS_DIR + '/Avatars'
require $APP_MODELS_DIR + '/Avatar'
require $APP_MODELS_DIR + '/Sandbox'
require $APP_MODELS_DIR + '/Lights'
require $APP_MODELS_DIR + '/Light'
require $APP_MODELS_DIR + '/Tags'
require $APP_MODELS_DIR + '/Tag'

require $LIB_DIR + '/TestRunner'
require $LIB_DIR + '/DockerTestRunner'
require $LIB_DIR + '/DummyGit'
require $LIB_DIR + '/DummyTestRunner'
require $LIB_DIR + '/FakeDisk'
require $LIB_DIR + '/Folders'
require $LIB_DIR + '/Git'
require $LIB_DIR + '/HostTestRunner'
require $LIB_DIR + '/OsDisk'
require $LIB_DIR + '/OsDir'
require $LIB_DIR + '/SpyDir'
require $LIB_DIR + '/SpyDisk'
require $LIB_DIR + '/SpyGit'
require $LIB_DIR + '/StubTestRunner'
