
me = File.dirname(__FILE__)
$CYBERDOJO_HOME_DIR = File.expand_path('..', me) + '/'

$LOAD_PATH << $CYBERDOJO_HOME_DIR + 'lib'
require 'DockerTestRunner'
require 'DummyGit'
require 'DummyTestRunner'
require 'FakeDisk'
require 'Folders'
require 'Git'
require 'HostTestRunner'
require 'OsDisk'
require 'OsDir'
require 'SpyDir'
require 'SpyDisk'
require 'SpyGit'
require 'StubTestRunner'

$LOAD_PATH << $CYBERDOJO_HOME_DIR + 'app/helpers'
require 'make_time_helper'

$LOAD_PATH << $CYBERDOJO_HOME_DIR + 'app/lib'
require 'Choose'
require 'FileDeltaMaker'
require 'GitDiff'
require 'GitDiffBuilder'
require 'GitDiffParser'
require 'LineSplitter'
require 'MakefileFilter'
require 'OutputParser'
require 'TdGapper'

$LOAD_PATH << $CYBERDOJO_HOME_DIR + 'app/models'
require 'Dojo'
require 'Languages'
require 'Language'
require 'Exercises'
require 'Exercise'
require 'Katas'
require 'Kata'
require 'Id'
require 'Avatars'
require 'Avatar'
require 'Sandbox'
require 'Lights'
require 'Light'
require 'Tags'
require 'Tag'
