#!/bin/bash

GIT_USER_NAME_BEFORE=`git config user.name`

echo $1
cat $1

#rm -rf ../../coverage/.resultset.json

#../testrb . 2>&1 | tee log.tmp
# WHICH EXECUTES THIS...

#cat test*.rb > _temp_all_tests.rb
# NOW HAVE TO TAIL IT
#ruby _temp_all_tests.rb
#rm _temp_all_tests.rb


#cp -R ../../coverage/* .
#ruby ../print_coverage_percent.rb index.html $1 | tee -a log.tmp


GIT_USER_NAME_AFTER=`git config user.name`

if [ "$GIT_USER_NAME_BEFORE" != "$GIT_USER_NAME_AFTER" ]; then
  echo "--------------------------------------"
  echo " META TEST FAILURE!"
  echo "--------------------------------------"
  echo "Before running testrb"
  echo '  >git config user.name'
  echo "  $GIT_USER_NAME_BEFORE"
  echo
  echo "After running testrb"
  echo '  >git config user.name'
  echo "  $GIT_USER_NAME_AFTER"
  echo "--------------------------------------"
fi