FROM busybox
MAINTAINER Jan Sørensen

# docker build -t cyberdojofoundation/katas-data .
# docker create --name cyber-dojo-katas-data-container cyberdojofoundation/katas-data

RUN mkdir -p /usr/src/app/katas

VOLUME ["/usr/src/app/katas"]

CMD ["not runnable - a data container"]
