FROM       cyberdojo/r-3.0.1
MAINTAINER Jon Jagger <jon@jaggersoft.com>

RUN apt-get -y install wget
RUN wget https://raw.githubusercontent.com/JonJagger/cyberdojo/master/languages/R-RUnit/install_RUnit.R
RUN Rscript install_RUnit.R