FROM cyberdojo/build-essential
MAINTAINER Jon Jagger <jon@jaggersoft.com>

RUN echo "deb http://archive.ubuntu.com/ubuntu saucy main universe" > /etc/apt/sources.list
RUN apt-get update
RUN apt-get upgrade -y

# docker build -t  cyberdojo/perl  .
# docker push      cyberdojo/perl
# docker run -i -t cyberdojo/perl /bin/bash
