#!/bin/bash

images=(exercises languages katas tmp rails web test nginx)

function build {
  DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
  pushd ${DIR} > /dev/null
  for image in ${images[*]}
  do
    pushd ${image} > /dev/null
    echo "---------------------------------------"
    echo "BUILDING: cyberdojofoundation/${image}"
    echo "---------------------------------------"
    ./build_docker_image.sh
    popd > /dev/null
  done
  popd > /dev/null
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - -

function push {
  for image in ${images[*]}
  do
    hub_image=cyberdojofoundation/${image}
    echo "---------------------------------------"
    echo "PUSHING: ${hub_image}"
    echo "---------------------------------------"
    docker push ${hub_image}
  done
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - -

function pull {
  for image in ${images[*]}
  do
    hub_image=cyberdojofoundation/${image}
    echo "---------------------------------------"
    echo "PULLING: ${hub_image}"
    echo "---------------------------------------"
    docker pull ${hub_image}
  done
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - -

function show_use {
  echo
  echo "USE: cdf [build | push | pull]"
  echo
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - -

if [ -z $1 ]; then
  show_use && exit
fi

if [ $1 = "build" ]; then
  build && exit
fi

if [ $1 = "push" ]; then
  push && exit
fi

if [ $1 = "pull" ]; then
  pull && exit
fi

show_use



