#!/bin/sh
set -e

ME="./$( basename ${0} )"
MY_DIR="$( cd "$( dirname "${0}" )" && pwd )"

HOME=/usr/src/cyber-dojo         # home folder *inside* the server image
REPO=cyberdojofoundation         # username on docker hub

ENV_DEFAULT=development          # TODO: FAILS for production!
ENV=${ENV_DEFAULT}               # rails server -e ${ENV}

RUNNER_DEFAULT=DockerKatasDataContainerRunner
RUNNER=${RUNNER_DEFAULT}         # See app/models/dojo.rb

DOCKER_COMPOSE_FILE=docker-compose.yml
DOCKER_COMPOSE_CMD="docker-compose --file=./${DOCKER_COMPOSE_FILE}"

# TOOD: USE THIS ONLY FOR 1st TIME CREATION OF KATAS-DATA-CONTAINER
HOST_KATAS_DEFAULT=/var/www/cyber-dojo/katas
HOST_KATAS=${HOST_KATAS_DEFAULT} # where katas are stored on the *host*
                                 # and get copied into the katas-data-container

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# TODO: add command to backup katas-data-container to tar.tgz file
# TODO: add command to delete runner cache inside web container

# TODO: detect if more than one command entered
# TODO: pull all language images == fetch? all?
# TODO: repo -> ls? -> lsi ?
# TODO: bootstrap= install_docker + pull_all_languages + up
# TODO: bootstrap= install_docker + pull_few_languages + up
#

show_use()
{
  echo
  echo "Usage: ${ME} COMMAND"
  echo "       ${ME} help"
  echo
  echo 'Commands:'
  echo
  echo '    install_docker    Installs docker, docker-machine, and docker-compose'
  echo
  echo '    ps                Lists server containers'
  echo '    start             Starts the server containers'
  echo '    stop              Stops the server containers'
  echo '    rm                Removes the server containers'
  echo '    up [OPTIONS]      Creates and starts the server containers'
  echo

  # options to build/backup the katas-data-container

  echo '    images            Lists pulled language images'
  echo '    pull=IMAGE        Pulls language IMAGE'
  echo '    repo              Lists all language images'
  echo '    rmi=IMAGE         Removes a pulled language IMAGE'
  echo '    upgrade           Pulls the latest server and language images'
  echo
  echo 'up [OPTIONS]:'
  echo
  echo "     katas=/var/www/cyber-dojo/katas     default=${HOST_KATAS_DEFAULT}"
  echo "       env=[development|production]      default=${ENV_DEFAULT}"
  echo "    runner=[CLASS_NAME]                  default=${RUNNER_DEFAULT}"
  echo
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# INSTALL DOCKER
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

INSTALL_DOCKER_CURL_CMD="curl -sSL https://get.docker.com/ | sh"

show_how_to_install_docker()
{
  echo
  echo 'To install docker:'
  echo "$ ${ME} install_docker"
  echo 'which does'
  echo "$ ${INSTALL_DOCKER_CURL_CMD}"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

INSTALL_DOCKER_MACHINE_CURL_CMD="curl -L https://github.com/docker/machine/releases/download/v0.6.0/docker-machine-`uname -s`-`uname -m` > /usr/local/bin/docker-machine"
INSTALL_DOCKER_MACHINE_CHMOD_CMD="chmod +x /usr/local/bin/docker-machine"

show_how_to_install_docker_machine()
{
  echo
  echo 'To install docker-machine:'
  echo "$ ${ME} install_docker"
  echo 'which does'
  echo "$ ${INSTALL_DOCKER_MACHINE_CURL_CMD}"
  echo "$ ${INSTALL_DOCKER_MACHINE_CHMOD_CMD}"
  echo 'To check for new releases visit https://docs.docker.com/machine/install-machine/'
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

INSTALL_DOCKER_COMPOSE_CURL_CMD="curl -L https://github.com/docker/compose/releases/download/1.6.0/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose"
INSTALL_DOCKER_COMPOSE_CHMOD_CMD="chmod +x /usr/local/bin/docker-compose"

show_how_to_install_docker_compose()
{
  echo
  echo 'To install docker-compose:'
  echo "$ ${ME} install_docker"
  echo 'which does'
  echo "$ ${INSTALL_DOCKER_COMPOSE_CURL_CMD}"
  echo "$ ${INSTALL_DOCKER_COMPOSE_CHMOD_CMD}"
  echo 'To check for new releases visit https://github.com/docker/compose/releases'
}

#========================================================================================
# CONTAINERS
#========================================================================================

ps()
{
  ${DOCKER_COMPOSE_CMD} ps
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

start()
{
  ${DOCKER_COMPOSE_CMD} start
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

stop()
{
  ${DOCKER_COMPOSE_CMD} stop
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

rm()
{
  ${DOCKER_COMPOSE_CMD} rm
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

up()
{
  # TODO: test in main flow?
  exit_if_bad_katas
  exit_if_bad_runner
  exit_if_bad_env
  pull_common_languages_if_none
  CWD=$(pwd)
  cd "${MY_DIR}" > /dev/null
  ${DOCKER_COMPOSE_CMD} up -d
  cd "${CWD}" > /dev/null
}

# - - - - - - - - - - - - - - - - - - - - - - - - -

exit_if_bad_env()
{
  if [ "${ENV}" != 'development' ] &&
     [ "${ENV}" != 'production' ];
  then
    echo "${ME}: env=${ENV} ?"
    echo "See ${ME} help"
    exit
  fi
  if [ "${ENV}" == 'production' ]; then
    # <<<<<<< TODO >>>>>>>>
    echo 'up env=production'
    echo '>>>> not supported yet'
    echo '>>>> Dockerfile currently hard-wires development'
    echo '>>>> up abandoned'
    exit
  fi
}

# - - - - - - - - - - - - - - - - - - - - - - - - -

exit_if_bad_katas()
{
  # overriding the default, dir must exist
  if [ "${HOST_KATAS}" != "${HOST_KATAS_DEFAULT}" ] && [ ! -d "${HOST_KATAS}" ]; then
    echo "${ME}: katas=${HOST_KATAS} ? ${HOST_KATAS} directory does not exist"
    echo "See ${ME} help"
    exit
  fi

  # TODO: if there is ALREADY a katas-data-container then return from this function

  # TODO:
  # if HOST_KATAS does not exist assume this server is new
  #   and create an empty katas-data-container
  #
  # TODO:
  # if HOST_KATAS does exist assume this server is replacing an existing one
  #   and create a full katas-data-container
  # being hosted where a previous (non dockerized) server lived.
}

# - - - - - - - - - - - - - - - - - - - - - - - - -

exit_if_bad_runner()
{
  # TODO: StubRunner for running tests inside the container?
  if [ "${RUNNER}" != 'DockerKatasDataContainerRunner' ] &&
     [ "${RUNNER}" != 'DockerMachineRunner' ];
  then
    echo "${ME}: runner=${RUNNER} ?"
    echo "See ${ME} help"
    exit
  fi
}

#========================================================================================
# IMAGES
#========================================================================================

pulled_language_images()
{
  ALL_LANGUAGE_IMAGES=$(echo "${LS_REPO}" | awk '{print $NF}' | sort)
  PULLED_IMAGES=$(docker images | grep ${REPO} | awk '{print $1}')
  SPLIT=$(echo "${PULLED_IMAGES}" | sed 's/\// /g')
  PULLED_IMAGES=$(echo "${SPLIT}" | awk '{print $NF}' | sort)

  TMP_FILE_1=/tmp/cyber-dojo.comm1.txt
  TMP_FILE_2=/tmp/cyber-dojo.comm2.txt
  echo "${ALL_LANGUAGE_IMAGES}" > ${TMP_FILE_1}
  echo       "${PULLED_IMAGES}" > ${TMP_FILE_2}
  comm -12 ${TMP_FILE_1} ${TMP_FILE_2}

  # These two lines cause docker containers to stop and I have no idea why?!
  #rm ${TMP_FILE_1}
  #rm ${TMP_FILE_2}
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

images()
{
  # FIXME: this gives the same as ls_repo when there are no languages pulled
  LS_REPO=$(repo)
  PULLED=$(pulled_language_images)
  echo "${LS_REPO}" | grep 'LANGUAGE'
  echo "${LS_REPO}" | grep "${PULLED}"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

install_docker()
{
  echo 'installing docker'
  eval ${INSTALL_DOCKER_CURL_CMD}
  echo 'installing docker-machine'
  eval ${INSTALL_DOCKER_MACHINE_CURL_CMD}
  eval ${INSTALL_DOCKER_MACHINE_CHMOD_CMD}
  echo 'installing docker-compose'
  eval ${INSTALL_DOCKER_COMPOSE_CURL_CMD}
  eval ${INSTALL_DOCKER_COMPOSE_CHMOD_CMD}
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

pull()
{
  docker pull ${REPO}/${IMAGE}:latest
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

repo()
{
  # will pull web image if necessary
  docker run --rm ${REPO}/web sh -c "./app/languages/list_all_images.rb"
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

rmi()
{
  docker rmi ${REPO}/${IMAGE}
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

pull_common_languages_if_none()
{
  LS_REPO=$(repo)
  PULLED=$(pulled_language_images)
  if [ -z "${PULLED}" ]; then
    echo 'No language images pulled'
    echo 'Pulling a small starting collection of common language images'
    IMAGE=gcc_assert
    pull
    #IMAGE=ruby_mini_test
    #pull
  fi
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

upgrade()
{
  echo "downloading latest ${DOCKER_COMPOSE_FILE} file"
  download_latest_docker_compose_yml
  echo 'upgrading cyber-dojo server images'
  CWD=$(pwd)
  cd "${MY_DIR}" > /dev/null
  SERVICES=`${DOCKER_COMPOSE_CMD} config --services 2> /dev/null`
  cd "${CWD}" > /dev/null
  echo "${SERVICES}" | while read IMAGE ; do
    pull
  done

  echo 'upgrading cyber-dojo pulled language images'
  LS_REPO=$(repo)
  PULLED=$(pulled_language_images)
  echo "${PULLED}" | while read IMAGE ; do
    pull
  done
}

download_latest_docker_compose_yml()
{
  CWD=$(pwd)
  cd "${MY_DIR}" > /dev/null
  curl -O https://raw.githubusercontent.com/JonJagger/cyber-dojo/master/docker/${DOCKER_COMPOSE_FILE}
  cd "${CWD}" > /dev/null
}

#========================================================================================
# PROCESS COMMAND LINE ARGS
#========================================================================================

for ARG in "$@"
do
  case ${ARG} in
    help)
      show_use
      exit
      ;;
    install_docker)
      doInstall=true
      ;;
    # - - - - - - - CONTAINERS - - - - - - - -
    ps)
      doPs=true
      ;;
    start)
      doStart=true
      ;;
    stop)
      doStop=true
      ;;
    rm)
      doRm=true
      ;;
    up)
      doUp=true
      ;;
    # - - - - - - - OPTIONS - - - - - - - -
    katas=*)
      KATAS="${ARG#*=}"
      ;;
    runner=*)
      RUNNER="${ARG#*=}"
      ;;
    env=*)
      ENV="${ARG#*=}"
      ;;
    # - - - - - - - IMAGES - - - - - - - -
    images)
      doImages=true
      ;;
    pull=*)
      IMAGE="${ARG#*=}"
      doPull=true
      ;;
    repo)
      doRepo=true
      ;;
    rmi=*)
      IMAGE="${ARG#*=}"
      doRmi=true
      ;;
    upgrade)
      doUpgrade=true
      ;;
    # - - - - - - - SOMETHING'S NOT RIGHT - - - - - - - -
    *)
      echo "${ME}: ${ARG} ?"
      echo "See '${ME} help"
      exit
      ;;
  esac
done

#========================================================================================
# INSTALL DOCKER OR SAY HOW TO
#========================================================================================

if [ -n "${doInstall}" ]; then
  install_docker
  exit
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

hash docker 2> /dev/null
if [ $? != 0  ]; then
  echo
  echo 'cyber-dojo requires docker'
  show_how_to_install_docker
  show_how_to_install_docker_machine
  show_how_to_install_docker_compose
  echo
  exit
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

hash docker-machine 2> /dev/null
if [  $? != 0 ]; then
  echo
  echo 'cyber-dojo requires docker-machine'
  show_how_to_install_docker_machine
  echo
  exit
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

hash docker-compose 2> /dev/null
if [  $? != 0 ]; then
  echo
  echo 'cyber-dojo requires docker-compose'
  show_how_to_install_docker_compose
  echo
  exit
fi

#========================================================================================
# NOTHING IS IMPLICIT
#========================================================================================

if [ $# -eq 0 ]; then
  show_use
  exit
fi

#========================================================================================
# YOU MUST HAVE THE YML FILE
#========================================================================================

if [ ! -e ${MY_DIR}/${DOCKER_COMPOSE_FILE} ]; then
  download_latest_docker_compose_yml
fi

#========================================================================================
# YML FILES RELIES ON THESE ENV-VARS
#========================================================================================

export CYBER_DOJO_ENV=${ENV}
export CYBER_DOJO_LANGUAGES_ROOT=${HOME}/app/languages
export CYBER_DOJO_EXERCISES_ROOT=${HOME}/app/exercises
export CYBER_DOJO_CACHES_ROOT=${HOME}/app/caches
export CYBER_DOJO_SHELL_CLASS=HostShell
export CYBER_DOJO_DISK_CLASS=HostDisk
export CYBER_DOJO_LOG_CLASS=HostLog
export CYBER_DOJO_GIT_CLASS=HostGit

export CYBER_DOJO_KATAS_ROOT=${HOME}/katas
export CYBER_DOJO_KATAS_CLASS=HostDiskKatas
export CYBER_DOJO_RUNNER_CLASS=${RUNNER}
export CYBER_DOJO_RUNNER_SUDO='sudo -u docker-runner sudo'

#========================================================================================
# DO SOMETHING!
#========================================================================================

if [ -n "${doPs}"      ]; then ps     ; exit; fi
if [ -n "${doStart}"   ]; then start  ; exit; fi
if [ -n "${doStop}"    ]; then stop   ; exit; fi
if [ -n "${doRm}"      ]; then rm     ; exit; fi
if [ -n "${doUp}"      ]; then up     ; exit; fi

if [ -n "${doImages}"  ]; then images ; exit; fi
if [ -n "${doPull}"    ]; then pull   ; exit; fi
if [ -n "${doRepo}"    ]; then repo   ; exit; fi
if [ -n "${doRmi}"     ]; then rmi    ; exit; fi
if [ -n "${doUpgrade}" ]; then upgrade; exit; fi
