FROM       cyberdojofoundation/groovy-2.4.4
MAINTAINER Jon Jagger <jon@jaggersoft.com>

RUN mkdir /groovy
RUN cp /groovy-2.4.4/embeddable/groovy-all-2.4.4.jar /groovy/
RUN cp /groovy-2.4.4/lib/hamcrest-core-1.3.jar /groovy/
RUN cp /groovy-2.4.4/lib/junit-4.12.jar /groovy/

ENV CLASSPATH=/groovy/
