FROM busybox
MAINTAINER Jon Jagger

RUN mkdir -p /var/www/cyber-dojo/languages
COPY ./languages /var/www/cyber-dojo/languages
VOLUME ["/var/www/cyber-dojo/languages"]
CMD ["not runnable - a data container"]
