FROM       cyberdojofoundation/groovy-2.4.4
MAINTAINER Jon Jagger <jon@jaggersoft.com>

ADD junit-dep-4.10.jar /groovy/
ADD groovy-all-2.0.5.jar /groovy/
ADD hamcrest-core-1.3.jar /groovy/
ADD spock-core-0.7-groovy-2.0.jar /groovy/

ENV CLASSPATH=/groovy/

