FROM       cyberdojo/groovy-2.2.0
MAINTAINER Jon Jagger <jon@jaggersoft.com>

ADD junit-4.11.jar /groovy/
ADD groovy-all-2.2.0.jar /groovy/
ADD hamcrest-core-1.3.jar /groovy/

ENV CLASSPATH=/groovy/

