apiVersion: v1
kind: Service
metadata:
  name: railsapp
  labels:
    app: railsapp
spec:
  type: NodePort
  selector:
    app: railsapp
  ports:
  - name: http
    nodePort: 80
    port: 80
    protocol: TCP
