FROM       cyberdojo/fsharp-3.0.26-1
MAINTAINER Jon Jagger <jon@jaggersoft.com>


RUN mono nuget.exe install NUnit -Version 2.6.2 -o Packages -ExcludeVersion
RUN mono nuget.exe install FsUnit -Version 1.2.1.0 -o Packages -ExcludeVersion

