FROM       cyberdojo/fsharp-3.0.26-1
MAINTAINER Jon Jagger <jon@jaggersoft.com>

RUN mono nuget.exe install NUnit  -o Packages -ExcludeVersion
RUN mono nuget.exe install FsUnit -o Packages -ExcludeVersion