FROM busybox
MAINTAINER Jan Sørensen

# docker build -t cyberdojofoundation/tmp-data .
# docker create --name cyber-dojo-tmp-data-container cyberdojofoundation/tmp-data

RUN mkdir -p /tmp

VOLUME ["/tmp"]

CMD ["not runnable - a data container"]
