FROM cyberdojofoundation/rails
MAINTAINER Jon Jagger <jon@jaggersoft.com>

ARG  CYBER_DOJO_ROOT

COPY pems      ${CYBER_DOJO_ROOT}/pems

COPY app       ${CYBER_DOJO_ROOT}/app
COPY config    ${CYBER_DOJO_ROOT}/config
COPY lib       ${CYBER_DOJO_ROOT}/lib

COPY script    ${CYBER_DOJO_ROOT}/script
COPY config.ru ${CYBER_DOJO_ROOT}

RUN mkdir      ${CYBER_DOJO_ROOT}/caches
RUN mkdir      ${CYBER_DOJO_ROOT}/log
RUN mkdir      ${CYBER_DOJO_ROOT}/tmp

CMD [ "bash", "-c", "rails server" ]
