FROM       cyberdojofoundation/build-essential
MAINTAINER Pablo Mansanet <pablo.mansanet@bluefruit.co.uk>

RUN apt-get update && apt-get install --yes software-properties-common
RUN add-apt-repository ppa:pgavin/ghdl
RUN apt-get update && apt-get install --yes ghdl
