FROM       cyberdojofoundation/build-essential
MAINTAINER Jon Jagger <jon@jaggersoft.com>

RUN apt-get update && apt-get install --yes curl
RUN curl -sSf https://static.rust-lang.org/rustup.sh | sh -s -- -y

