FROM       cyberdojofoundation/java-1.8
MAINTAINER Jon Jagger <jon@jaggersoft.com>

# docker build -t cyberdojofoundation/java_powermockito .

COPY /jars/* /powermockito/
ENV CLASSPATH=/powermockito/

