FROM cyberdojofoundation/user-base
MAINTAINER Jon Jagger <jon@jaggersoft.com>

ARG CYBER_DOJO_KATAS_ROOT
USER root
RUN  mkdir -p ${CYBER_DOJO_KATAS_ROOT}
COPY . ${CYBER_DOJO_KATAS_ROOT}
RUN  chown -R cyber-dojo ${CYBER_DOJO_KATAS_ROOT
VOLUME [ "${CYBER_DOJO_KATAS_ROOT}" ]
CMD [ "katas-data-container" ]
