FROM       cyberdojo/build-essential
MAINTAINER Jon Jagger <jon@jaggersoft.com>

# docker build -t  cyberdojo/gcc-4.8.1 .
# docker push      cyberdojo/gcc-4.8.1
# docker run -i -t cyberdojo/gcc-4.8.1 /bin/bash
