FROM       cyberdojo/gcc-4.8.1
MAINTAINER Jon Jagger <jon@jaggersoft.com>

# docker build -t  cyberdojo/gcc-4.8.1_assert .
# docker push      cyberdojo/gcc-4.8.1_assert
# docker run -i -t cyberdojo/gcc-4.8.1_assert /bin/bash
